apiVersion: v1
kind: Namespace
metadata:
  labels:
    namespaceclass.akuity.io/name: public-network
  name: daochun-public
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    namespaceclass.akuity.io/name: internal-network
  name: daochun-internal
spec:
  finalizers:
    - kubernetes
---
apiVersion: core.akuity.io/v1
kind: NamespaceClass
metadata:
  name: public-network
---
apiVersion: core.akuity.io/v1
kind: NamespaceClass
metadata:
  name: internal-network
